from app.models.audit_log import AuditLog
from app.models.razon_social import RazonSocial
from app.models.role import Role
from app.models.session import UserSession
from app.models.sot_reporte import SotReporte
from app.models.sync_log import SyncLog
from app.models.user import User
from app.models.user_email import UserEmail
from app.models.user_phone import UserPhone
from app.models.user_razon_social import UserRazonSocial
from app.models.user_supervisor import UserSupervisor
